linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errorlint
    # - exhaustive
    - exportloopref
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goimports
    # - gomnd
    - gomodguard
    - gosec
    - interfacer
    - maligned
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - prealloc
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
    - wsl
    - paralleltest
